-- 1. DATABASE & SCHEMAS

CREATE DATABASE IF NOT EXISTS PERMAFROST_POC;
USE DATABASE PERMAFROST_POC;


CREATE SCHEMA IF NOT EXISTS PERMAFROST_POC.INGEST;
CREATE SCHEMA IF NOT EXISTS PERMAFROST_POC.PROCESSING;
CREATE SCHEMA IF NOT EXISTS PERMAFROST_POC.AUDIT;
CREATE SCHEMA IF NOT EXISTS PERMAFROST_POC.CONFIG;

-- 2. INTERNAL STAGES

CREATE STAGE IF NOT EXISTS PERMAFROST_POC.INGEST.RAW_DOCUMENTS_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE); -- Store sample raw documents for PoC Phase

CREATE STAGE IF NOT EXISTS PERMAFROST_POC.PROCESSING.PROCESSED_DOC_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE); -- Store processed documents


-- 3. Set up Config Schema Tables

CREATE FILE FORMAT IF NOT EXISTS PERMAFROST_POC.CONFIG.JSON_RAW_FORMAT
TYPE = 'JSON'
STRIP_OUTER_ARRAY = FALSE
COMPRESSION = 'NONE'
COMMENT = 'Used by notebooks to read JSON config files from stage';

-- Document type schema registry (one row per doc type)
CREATE TABLE IF NOT EXISTS PERMAFROST_POC.CONFIG.DOC_TYPE_CONFIG (
    DOC_TYPE VARCHAR(100) NOT NULL,
    DOC_DISPLAY_NAME VARCHAR(200),
    SCHEMA_VERSION VARCHAR(20) DEFAULT '1.0',
    MANDATORY_FIELDS VARIANT NOT NULL,
    OPTIONAL_FIELDS VARIANT,                     -- same shape as above
    SYNONYMS VARIANT,                     -- {field_id: [synonym_label, ...]}
    CONFIDENCE_THRESHOLDS VARIANT,
    -- {field_completeness, field_extract_confidence}
    CONFIDENCE_WEIGHTS VARIANT,
    --if fall back to AI_COMPLETE for extraction
    PROMPT_TEMPLATE VARCHAR(16777216),
    LLM_MODEL VARCHAR(100), -- model used for AI_COMPLETE
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    DEDUP_KEY_FIELDS VARIANT, --TBD
    CONSTRAINT PK_DOC_TYPE_CONFIG PRIMARY KEY (DOC_TYPE)
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.CONFIG.PIPELINE_CONFIG (
    CONFIG_KEY VARCHAR(200) NOT NULL,
    CONFIG_VALUE VARCHAR(16777216) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    VERSION_NUMBER NUMBER DEFAULT 1,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    UPDATED_BY VARCHAR(200),
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PIPELINE_CONFIG PRIMARY KEY (CONFIG_KEY, VERSION_NUMBER)
);

-- 4. Set Ingestion Tables

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.INGEST.DOCUMENTS_INGESTED (
    DOC_ID VARCHAR(36) NOT NULL,
    -- points to original Excel DOC_ID for converted PDFs; NULL otherwise
    SOURCE_ORIGIN_DOC_ID VARCHAR(36),
    -- 'batch_stage' | 'pipeline_conversion'
    SOURCE_CHANNEL VARCHAR(50) NOT NULL,
    SOURCE_FORMAT VARCHAR(20),              -- original file extension
    ORIGINAL_FILENAME VARCHAR(500) NOT NULL,
    STAGE_PATH VARCHAR(1000) NOT NULL,
    FILE_HASH_SHA256 VARCHAR(64),
    FILE_SIZE_BYTES NUMBER,
    -- NULL; set by classify for split children
    SOURCE_PAGE_START NUMBER,
    SOURCE_PAGE_END NUMBER,
    DUPLICATE_OF VARCHAR(36),
    RECEIVED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    UPLOADED_BY VARCHAR(200),
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    CONSTRAINT PK_DOCUMENTS_INGESTED PRIMARY KEY (DOC_ID)
);

-- 5. Set Processing Tables
CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.DOCUMENTS_TEXT (
    DOC_ID VARCHAR(36) NOT NULL,
    EXTRACTED_TEXT VARCHAR(16777216) NOT NULL,
    RAW_EXTRACTED_VALUE VARIANT,
    PAGE_COUNT NUMBER(38, 0),
    EXTRACTION_MODEL VARCHAR(100),
    EXTRACTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.DOCUMENTS_PAGES (
    DOC_ID VARCHAR(36) NOT NULL,
    CHILD_DOC_ID VARCHAR(36), -- to be added in classify
    PAGE_INDEX NUMBER NOT NULL,
    PAGE_NUMBER NUMBER NOT NULL,
    PAGE_CONTENT VARCHAR(16777216) NOT NULL,
    PAGE_CONTENT_TRANSLATED VARCHAR(16777216),
    PAGE_CONTENT_REDACTED VARCHAR(16777216),
    EXTRACTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    LANGUAGE_RESULT VARCHAR,
    LANGUAGE_CHECKED_AT TIMESTAMP_TZ,
    LANGUAGE_CLASSIFICATION_REASON VARCHAR,
    CONSTRAINT PK_DOCUMENTS_PAGES PRIMARY KEY (DOC_ID, PAGE_INDEX)
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.DOCUMENTS_CLASSIFIED (
    -- new UUID per segment; = DOC_ID if no split
    CHILD_DOC_ID VARCHAR(36) NOT NULL,
    DOC_ID VARCHAR(36) NOT NULL,      -- DOC_ID from DOCUMENTS_INGESTED
    -- classified doc type for this segment
    DOC_TYPE VARCHAR(100),
    DOC_TYPE_LABEL VARCHAR(200),
    PAGE_START NUMBER NOT NULL,
    PAGE_END NUMBER NOT NULL,
    -- classify confidence for this segment
    CONFIDENCE FLOAT,
    BOUNDARY_SIGNAL VARCHAR(500),
    DOCUMENT_DESCRIPTION VARCHAR(2000),
    CLASSIFIED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOCUMENTS_CLASSIFIED PRIMARY KEY (CHILD_DOC_ID)
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.DOCUMENTS_PII (
    PII_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    DOC_ID VARCHAR(36),
    CHILD_DOC_ID VARCHAR(36),
    FIELD_ID VARCHAR(200),           -- NULL for page scan, set for field scan
    FIELD_VALUE VARCHAR,               -- actual PII text that was detected
    PII_CATEGORY VARCHAR(100),           -- NAME | EMAIL | PHONE_NUMBER etc
    RECORDED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOCUMENTS_PII PRIMARY KEY (PII_ID)
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.DOCUMENTS_EXTRACTED (
    CHILD_DOC_ID VARCHAR(36) NOT NULL,
    DOC_TYPE VARCHAR(100),
    EXTRACTED_JSON VARIANT,
    EXTRACTION_MODEL VARCHAR(100),
    EXTRACTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOCUMENTS_EXTRACTED PRIMARY KEY (CHILD_DOC_ID)
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.DOCUMENTS_EXTRACTED_FLAT (
    CHILD_DOC_ID VARCHAR(36) NOT NULL,
    FIELD_ID VARCHAR(200) NOT NULL,
    FIELD_VALUE VARCHAR,
    FIELD_CONFIDENCE FLOAT,
    EXTRACTION_MODEL VARCHAR(100),
    IS_MANDATORY BOOLEAN,
    IS_MISSING BOOLEAN,
    SOURCE_PAGE NUMBER,
    SOURCE_LABEL VARCHAR(100),
    IS_CROSS_DOC BOOLEAN DEFAULT FALSE,
    SOURCE_DOC_LABEL VARCHAR(100),
    SOURCE_CHILD_DOC_ID VARCHAR(36),
    REVIEWED_VALUE VARCHAR,
    CONSTRAINT PK_DOCUMENTS_EXTRACTED_FLAT
    PRIMARY KEY (CHILD_DOC_ID, FIELD_ID)
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.DOCUMENTS_SCORED (
    CHILD_DOC_ID VARCHAR(36) NOT NULL,
    EXTRACTION_MODEL VARCHAR(100),
    CLASSIFY_CONFIDENCE FLOAT,
    FIELD_COMPLETENESS FLOAT,
    EXTRACT_CERTAINTY FLOAT,
    COMPOSITE_SCORE FLOAT,
    GATE_RESULT VARCHAR(20),
    FLAG_REASONS VARIANT,
    SCORED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOCUMENTS_SCORED
    PRIMARY KEY (CHILD_DOC_ID, EXTRACTION_MODEL)
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.REVIEW_QUEUE (
    QUEUE_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    CHILD_DOC_ID VARCHAR(36) NOT NULL,
    DOC_TYPE VARCHAR(100),
    COMPOSITE_SCORE FLOAT,
    FLAG_REASONS VARIANT,
    NOTES VARCHAR(2000),
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    QUEUED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    REVIEWED_AT TIMESTAMP_TZ,
    CONSTRAINT PK_REVIEW_QUEUE PRIMARY KEY (QUEUE_ID)
);

-- Set Audit Tables

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.AUDIT.LLM_USAGE (
    USAGE_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    DOC_ID VARCHAR(36),
    CHILD_DOC_ID VARCHAR(36),
    PIPELINE_STEP VARCHAR(100),
    MODEL_NAME VARCHAR(100),
    TOKENS_IN NUMBER,
    TOKENS_OUT NUMBER,
    CALLED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LLM_USAGE PRIMARY KEY (USAGE_ID)
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.AUDIT.REVIEW_AUDIT_LOG (
    EVENT_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    DOC_ID VARCHAR(36) NOT NULL,
    CHILD_DOC_ID VARCHAR(36) NOT NULL,
    ORIGINAL_FILENAME VARCHAR(1000),
    STAGE_PATH VARCHAR(1000),
    DOC_TYPE VARCHAR(100),
    EVENT_TYPE VARCHAR(50) NOT NULL,
    ACTIVITY_NOTES VARCHAR(2000),
    PERFORMED_BY VARCHAR(200),
    EVENT_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_REVIEW_AUDIT_LOG PRIMARY KEY (EVENT_ID)
);


CREATE OR REPLACE VIEW PERMAFROST_POC.PROCESSING.VW_EXTRACTION_OUTPUT AS
WITH LATEST_QUEUE AS (
    SELECT
        CHILD_DOC_ID,
        STATUS AS QUEUE_STATUS
    FROM PERMAFROST_POC.PROCESSING.REVIEW_QUEUE
    QUALIFY
        ROW_NUMBER() OVER (PARTITION BY CHILD_DOC_ID ORDER BY QUEUED_AT DESC)
        = 1
),

APPROVALS AS (
    SELECT
        CHILD_DOC_ID,
        PERFORMED_BY AS REVIEWED_BY,
        EVENT_AT AS REVIEWED_AT
    FROM PERMAFROST_POC.AUDIT.REVIEW_AUDIT_LOG
    WHERE EVENT_TYPE = 'APPROVED'
    QUALIFY
        ROW_NUMBER() OVER (PARTITION BY CHILD_DOC_ID ORDER BY EVENT_AT DESC) = 1
)

SELECT
    F.CHILD_DOC_ID,
    C.DOC_ID,
    C.DOC_TYPE,
    I.ORIGINAL_FILENAME AS ORIGINAL_FILE_NAME,
    F.FIELD_ID,
    F.IS_MANDATORY,
    NULLIF(COALESCE(F.REVIEWED_VALUE, F.FIELD_VALUE), '') AS FIELD_VALUE,
    NULLIF(COALESCE(F.REVIEWED_VALUE, F.FIELD_VALUE), '') IS NULL AS IS_MISSING,
    CASE
        WHEN F.REVIEWED_VALUE IS NOT NULL THEN 'HUMAN_EDITED'
        WHEN SC.GATE_RESULT = 'AUTO_APPROVE' THEN 'AI_AUTO'
        ELSE 'AI_CONFIRMED'
    END AS VALUE_SOURCE
FROM PERMAFROST_POC.PROCESSING.DOCUMENTS_EXTRACTED_FLAT AS F
INNER JOIN PERMAFROST_POC.PROCESSING.DOCUMENTS_CLASSIFIED AS C
    ON F.CHILD_DOC_ID = C.CHILD_DOC_ID
INNER JOIN PERMAFROST_POC.INGEST.DOCUMENTS_INGESTED AS I
    ON C.DOC_ID = I.DOC_ID
INNER JOIN PERMAFROST_POC.PROCESSING.DOCUMENTS_SCORED AS SC
    ON
        F.CHILD_DOC_ID = SC.CHILD_DOC_ID
        AND F.EXTRACTION_MODEL = SC.EXTRACTION_MODEL
LEFT JOIN LATEST_QUEUE AS Q
    ON F.CHILD_DOC_ID = Q.CHILD_DOC_ID
LEFT JOIN APPROVALS AS A
    ON F.CHILD_DOC_ID = A.CHILD_DOC_ID
WHERE
    SC.GATE_RESULT = 'AUTO_APPROVE'
    OR (SC.GATE_RESULT = 'HUMAN_REVIEW' AND Q.QUEUE_STATUS = 'APPROVED');

-- doc type export view and supporting FUNCTION

CREATE OR REPLACE FUNCTION PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(V VARCHAR)
RETURNS VARCHAR
AS
$$
    CASE
        WHEN V IS NULL OR V = '' THEN NULL
        WHEN REGEXP_LIKE(V, '^\\[\\s*[''"].*[''"]\\s*\\]$', 's') THEN
            REGEXP_REPLACE(
                REGEXP_REPLACE(V, '^\\[\\s*[''"]|[''"]\\s*\\]$', ''),
                '[''"]\\s*,\\s*[''"]', '; ')
        ELSE V
    END
$$;

CREATE OR REPLACE VIEW PERMAFROST_POC.PROCESSING.VW_EXPORT_COMMERCIAL_INVOICE AS
SELECT
    CHILD_DOC_ID,
    DOC_ID,
    ORIGINAL_FILE_NAME,
    IFF(
        COUNT_IF(VALUE_SOURCE = 'HUMAN_EDITED') > 0,
        'HUMAN_EDITED',
        MAX(VALUE_SOURCE)
    ) AS DOC_VALUE_SOURCE,
    COUNT_IF(VALUE_SOURCE = 'HUMAN_EDITED') AS EDITED_FIELD_COUNT,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'invoice_number', FIELD_VALUE, NULL))
    ) AS INVOICE_NUMBER,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'purchase_order_number', FIELD_VALUE, NULL))
    ) AS PURCHASE_ORDER_NUMBER,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'document_date', FIELD_VALUE, NULL))
    ) AS DOCUMENT_DATE,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'supplier_name', FIELD_VALUE, NULL))
    ) AS SUPPLIER_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'supplier_address', FIELD_VALUE, NULL))
    ) AS SUPPLIER_ADDRESS,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'facility_name', FIELD_VALUE, NULL))
    ) AS FACILITY_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'facility_address', FIELD_VALUE, NULL))
    ) AS FACILITY_ADDRESS,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'country_of_origin', FIELD_VALUE, NULL))
    ) AS COUNTRY_OF_ORIGIN,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'country_of_processing', FIELD_VALUE, NULL))
    ) AS COUNTRY_OF_PROCESSING,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'species_common_name', FIELD_VALUE, NULL))
    ) AS SPECIES_COMMON_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'species_scientific_name', FIELD_VALUE, NULL))
    ) AS SPECIES_SCIENTIFIC_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'hts_codes', FIELD_VALUE, NULL))
    ) AS HTS_CODES
FROM PERMAFROST_POC.PROCESSING.VW_EXTRACTION_OUTPUT
WHERE DOC_TYPE = 'commercial_invoice'
GROUP BY CHILD_DOC_ID, DOC_ID, ORIGINAL_FILE_NAME;


CREATE OR REPLACE VIEW PERMAFROST_POC.PROCESSING.VW_EXPORT_HEALTH_CERTIFICATE AS
SELECT
    CHILD_DOC_ID,
    DOC_ID,
    ORIGINAL_FILE_NAME,
    IFF(
        COUNT_IF(VALUE_SOURCE = 'HUMAN_EDITED') > 0,
        'HUMAN_EDITED',
        MAX(VALUE_SOURCE)
    ) AS DOC_VALUE_SOURCE,
    COUNT_IF(VALUE_SOURCE = 'HUMAN_EDITED') AS EDITED_FIELD_COUNT,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'certificate_number', FIELD_VALUE, NULL))
    ) AS CERTIFICATE_NUMBER,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'document_date', FIELD_VALUE, NULL))
    ) AS DOCUMENT_DATE,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'supplier_name', FIELD_VALUE, NULL))
    ) AS SUPPLIER_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'supplier_address', FIELD_VALUE, NULL))
    ) AS SUPPLIER_ADDRESS,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'establishment_number', FIELD_VALUE, NULL))
    ) AS ESTABLISHMENT_NUMBER,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'species_common_name', FIELD_VALUE, NULL))
    ) AS SPECIES_COMMON_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'species_scientific_name', FIELD_VALUE, NULL))
    ) AS SPECIES_SCIENTIFIC_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'lot_number', FIELD_VALUE, NULL))
    ) AS LOT_NUMBER,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'production_date', FIELD_VALUE, NULL))
    ) AS PRODUCTION_DATE,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'expiry_date', FIELD_VALUE, NULL))
    ) AS EXPIRY_DATE,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'farm_identifier', FIELD_VALUE, NULL))
    ) AS FARM_IDENTIFIER
FROM PERMAFROST_POC.PROCESSING.VW_EXTRACTION_OUTPUT
WHERE DOC_TYPE = 'health_certificate'
GROUP BY CHILD_DOC_ID, DOC_ID, ORIGINAL_FILE_NAME;


CREATE OR REPLACE VIEW PERMAFROST_POC.PROCESSING.VW_EXPORT_CATCH_CERTIFICATE AS
SELECT
    CHILD_DOC_ID,
    DOC_ID,
    ORIGINAL_FILE_NAME,
    IFF(
        COUNT_IF(VALUE_SOURCE = 'HUMAN_EDITED') > 0,
        'HUMAN_EDITED',
        MAX(VALUE_SOURCE)
    ) AS DOC_VALUE_SOURCE,
    COUNT_IF(VALUE_SOURCE = 'HUMAN_EDITED') AS EDITED_FIELD_COUNT,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'certificate_number', FIELD_VALUE, NULL))
    ) AS CERTIFICATE_NUMBER,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'document_date', FIELD_VALUE, NULL))
    ) AS DOCUMENT_DATE,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'validating_authority', FIELD_VALUE, NULL))
    ) AS VALIDATING_AUTHORITY,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'supplier_name', FIELD_VALUE, NULL))
    ) AS SUPPLIER_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'supplier_address', FIELD_VALUE, NULL))
    ) AS SUPPLIER_ADDRESS,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'species_common_name', FIELD_VALUE, NULL))
    ) AS SPECIES_COMMON_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'species_scientific_name', FIELD_VALUE, NULL))
    ) AS SPECIES_SCIENTIFIC_NAME,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'product_code', FIELD_VALUE, NULL))
    ) AS PRODUCT_CODE,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'catch_area', FIELD_VALUE, NULL))
    ) AS CATCH_AREA,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'catch_date', FIELD_VALUE, NULL))
    ) AS CATCH_DATE,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'fishing_gear', FIELD_VALUE, NULL))
    ) AS FISHING_GEAR,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'vessel_names', FIELD_VALUE, NULL))
    ) AS VESSEL_NAMES,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'vessel_registration_numbers', FIELD_VALUE, NULL))
    ) AS VESSEL_REGISTRATION_NUMBERS,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'vessel_imo_number', FIELD_VALUE, NULL))
    ) AS VESSEL_IMO_NUMBER,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'vessel_permit_number', FIELD_VALUE, NULL))
    ) AS VESSEL_PERMIT_NUMBER,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'vessel_flag_state', FIELD_VALUE, NULL))
    ) AS VESSEL_FLAG_STATE,
    PERMAFROST_POC.PROCESSING.FMT_LIST_VALUE(
        MAX(IFF(FIELD_ID = 'receiving_vessel_names', FIELD_VALUE, NULL))
    ) AS RECEIVING_VESSEL_NAMES
FROM PERMAFROST_POC.PROCESSING.VW_EXTRACTION_OUTPUT
WHERE DOC_TYPE = 'catch_certificate'
GROUP BY CHILD_DOC_ID, DOC_ID, ORIGINAL_FILE_NAME;
