-- 1. DATABASE & SCHEMAS

CREATE DATABASE IF NOT EXISTS PERMAFROST_POC;
USE DATABASE PERMAFROST_POC;


CREATE SCHEMA IF NOT EXISTS PERMAFROST_POC.INGEST;
CREATE SCHEMA IF NOT EXISTS PERMAFROST_POC.PROCESSING;
CREATE SCHEMA IF NOT EXISTS PERMAFROST_POC.AUDIT;
CREATE SCHEMA IF NOT EXISTS PERMAFROST_POC.CONFIG;

-- 2. INTERNAL STAGES

CREATE STAGE IF NOT EXISTS PERMAFROST_POC.INGEST.RAW_DOCUMENTS_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE); -- Store sample raw documents for PoC Phase

CREATE STAGE IF NOT EXISTS PERMAFROST_POC.PROCESSING.PROCESSED_DOC_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE); -- Store processed documents


-- 3. Set up Config Schema Tables

CREATE FILE FORMAT IF NOT EXISTS PERMAFROST_POC.CONFIG.JSON_RAW_FORMAT
TYPE = 'JSON'
STRIP_OUTER_ARRAY = FALSE
COMPRESSION = 'NONE'
COMMENT = 'Used by notebooks to read JSON config files from stage';

-- Document type schema registry (one row per doc type)
CREATE TABLE IF NOT EXISTS PERMAFROST_POC.CONFIG.DOC_TYPE_CONFIG (
    DOC_TYPE VARCHAR(100) NOT NULL,
    DOC_DISPLAY_NAME VARCHAR(200),
    SCHEMA_VERSION VARCHAR(20) DEFAULT '1.0',
    MANDATORY_FIELDS VARIANT NOT NULL,
    OPTIONAL_FIELDS VARIANT,                     -- same shape as above
    SYNONYMS VARIANT,                     -- {field_id: [synonym_label, ...]}
    CONFIDENCE_THRESHOLDS VARIANT,
    -- {field_completeness, field_extract_confidence}
    CONFIDENCE_WEIGHTS VARIANT,
    --if fall back to AI_COMPLETE for extraction
    PROMPT_TEMPLATE VARCHAR(16777216),
    LLM_MODEL VARCHAR(100), -- model used for AI_COMPLETE
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    DEDUP_KEY_FIELDS VARIANT, --TBD
    CONSTRAINT PK_DOC_TYPE_CONFIG PRIMARY KEY (DOC_TYPE)
);


-- 4. Set Ingestion Tables

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.INGEST.DOCUMENTS_INGESTED (
    DOC_ID VARCHAR(36) NOT NULL,
    -- NULL until classify splits a file
    PARENT_FILE_ID VARCHAR(36),
    -- points to original Excel DOC_ID for converted PDFs; NULL otherwise
    SOURCE_ORIGIN_DOC_ID VARCHAR(36),
    -- 'batch_stage' | 'pipeline_conversion'
    SOURCE_CHANNEL VARCHAR(50) NOT NULL,
    SOURCE_FORMAT VARCHAR(20),              -- original file extension
    ORIGINAL_FILENAME VARCHAR(500) NOT NULL,
    STAGE_PATH VARCHAR(1000) NOT NULL,
    FILE_HASH_SHA256 VARCHAR(64),
    FILE_SIZE_BYTES NUMBER,
    -- NULL; set by classify for split children
    SOURCE_PAGE_START NUMBER,
    SOURCE_PAGE_END NUMBER,
    DUPLICATE_OF VARCHAR(36),
    RECEIVED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    UPLOADED_BY VARCHAR(200),
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    CONSTRAINT PK_DOCUMENTS_INGESTED PRIMARY KEY (DOC_ID)
);

-- 5. Set Processing Tables
CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.DOCUMENTS_TEXT (
    DOC_ID VARCHAR(36) NOT NULL,
    EXTRACTED_TEXT VARCHAR(16777216) NOT NULL,
    PAGE_COUNT NUMBER(38, 0),
    EXTRACTION_MODEL VARCHAR(100),
    EXTRACTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PERMAFROST_POC.PROCESSING.DOCUMENTS_PAGES (
    DOC_ID VARCHAR(36) NOT NULL,
    PAGE_INDEX NUMBER NOT NULL,
    PAGE_NUMBER NUMBER NOT NULL,
    PAGE_CONTENT VARCHAR(16777216) NOT NULL,
    PAGE_CONTENT_TRANSLATED VARCHAR(16777216),
    EXTRACTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOCUMENTS_PAGES PRIMARY KEY (DOC_ID, PAGE_INDEX)
);
