# This file can be used to set a custom theme for your Streamlit. See
# https://docs.streamlit.io/develop/concepts/configuration/theming for more
# information.

[theme]
base = "dark"
primaryColor = "#0d6e6e"
backgroundColor = "#1e2022"
secondaryBackgroundColor = "#252729"
textColor = "#e8e5e0"
font = "sans serif"